name: Scan External URLs with Paths
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 0 * * 0'  # Weekly auto run (optional)
jobs:
  scan-urls:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Install curl and TruffleHog
      run: |
        sudo apt-get update
        sudo apt-get install -y curl
        curl -sSfL https://raw.githubusercontent.com/trufflesecurity/trufflehog/main/scripts/install.sh | sh -s -- -b /usr/local/bin
    - name: Generate Full URLs with Auto HTTPS
      run: |
        # Clean and combine domains with paths using awk
        awk '!/^\s*$/{gsub(/^[ \t]+|[ \t]+$/, "", $0); print}' domains.txt > domains_clean.txt
        awk '!/^\s*$/{gsub(/^[ \t]+|[ \t]+$/, "", $0); print}' paths.txt > paths_clean.txt
        awk '{domain=$0; if (domain !~ /^https?:\/\//) domain="https://"domain; while ((getline path < "paths_clean.txt") > 0) {gsub(/^[ \t\/]+|[ \t\/]+$/, "", path); print domain"/"path}}' domains_clean.txt > full_urls.txt
        # Limit to 1000 URLs (adjust as needed)
        head -n 1000 full_urls.txt > full_urls_limited.txt
        mv full_urls_limited.txt full_urls.txt
        # Clean empty lines and invalid characters
        awk 'NF' full_urls.txt > full_urls_clean.txt
        mv full_urls_clean.txt full_urls.txt
        echo "Generated $(wc -l < full_urls.txt) URLs"
        # Debug: Show first few URLs
        head -n 5 full_urls.txt
    - name: Scan Each URL with TruffleHog
      run: |
        # Ensure all URLs are scanned
        while IFS= read -r url || [[ -n "$url" ]]; do
          # Skip empty lines
          if [ -z "$url" ]; then
            continue
          fi
          echo "Scanning $url"
          # Clean URL for file name
          clean_url=$(echo "$url" | sed 's|https\?://||g' | tr '/:.' '___')
          trufflehog http --url "$url" --config .trufflehog.yml --only-verified --json > "trufflehog-report-${clean_url}.json" || true
        done < full_urls.txt
        echo "Scanned $(wc -l < full_urls.txt) URLs"
    - name: Upload Reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: scan-report
        path: trufflehog-report-*.json
