name: Scan External URLs with Paths
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 0 * * 0'  # Weekly auto run (optional)
jobs:
  scan-urls:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Install curl and TruffleHog
      run: |
        sudo apt-get update
        sudo apt-get install -y curl
        curl -sSfL https://raw.githubusercontent.com/trufflesecurity/trufflehog/main/scripts/install.sh | sh -s -- -b /usr/local/bin
    - name: Generate Full URLs with Auto HTTPS
      run: |
        # Bash script to add https:// and combine domains with paths
        while IFS= read -r domain; do
          # Add https:// if not present
          if [[ ! "$domain" =~ ^https?:// ]]; then
            domain="https://$domain"
          fi
          while IFS= read -r path; do
            # Remove leading/trailing slashes for clean URL
            clean_domain=$(echo "$domain" | sed 's|/$||')
            clean_path=$(echo "$path" | sed 's|^/||')
            full_url="${clean_domain}/${clean_path}"
            echo "$full_url" >> full_urls.txt
          done < paths.txt
        done < domains.txt
    - name: Scan Each URL with TruffleHog
      run: |
        # Loop through each URL and scan with TruffleHog
        while IFS= read -r url; do
          echo "Scanning $url"
          trufflehog http --url "$url" --config .trufflehog.yml --only-verified --json > "trufflehog-report-$(echo $url | tr '/' '_').json" || true
        done < full_urls.txt
    - name: Upload Reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: scan-report
        path: trufflehog-report-*.json
